name: Generate and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies 👨🏻‍💻
        run: yarn
      - name: Generate static page
        run: |
          touch .env
          echo CTF_CDA_ACCESS_TOKEN="85Q0rhBP9nC80sP3go1CEQIRLUZYyVovYahwluoVMQk" > .env
          echo CTF_PERSON_ID="15jwOBqpxqSAOy2eOO4S0m" >> .env
          echo CTF_PREVIEW_ACCESS_TOKEN="Pxp38o7fUMQfIii6s9uG7iKLx9K9vqK" >> .env
          echo CTF_SPACE_ID="0zag513o0dj7" >> .env
          yarn generate
        working-directory: ./
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          BRANCH: gh-pages
          FOLDER: dist
