name: Generate and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies 👨🏻‍💻
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Generate static page
        env:
          CTF_PERSON_ID: ${{ secrets.CTF_PERSON_ID }}
          CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
          CTF_CDA_ACCESS_TOKEN: ${{ secrets.CTF_CDA_ACCESS_TOKEN }}
          CTF_PREVIEW_ACCESS_TOKEN: ${{ secrets.CTF_PREVIEW_ACCESS_TOKEN }}
        run: yarn generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          BRANCH: gh-pages
          FOLDER: dist
