name: Generate and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies 👨🏻‍💻
        run: yarn
      - name: Generate static page
        run: |
          touch .env
          echo CTF_CDA_ACCESS_TOKEN="${{ secrets.CTF_CDA_ACCESS_TOKEN}}" > .env
          echo CTF_PERSON_ID="${{ secrets.CTF_PERSON_ID}}" >> .env
          echo CTF_PREVIEW_ACCESS_TOKEN="${{ secrets.CTF_PREVIEW_ACCESS_TOKEN}}" >> .env
          echo CTF_SPACE_ID="${{ secrets.CTF_SPACE_ID}}" >> .env
          yarn generate
        working-directory: ./
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          BRANCH: gh-pages
          FOLDER: dist
