name: Generate and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies 👨🏻‍💻
        run: yarn
      - name: Generate static page
        env:
          CTF_PERSON_ID: "15jwOBqpxqSAOy2eOO4S0m"
          CTF_SPACE_ID: "0zag513o0dj7"
          CTF_CDA_ACCESS_TOKEN: "85Q0rhBP9nC80sP3go1CEQIRLUZYyVovYahwluoVMQk"
          CTF_PREVIEW_ACCESS_TOKEN: "Pxp38o7fUMQfIii6s9uG7iKLx9K9vqK-cZ8dwU3s8rA"
        run: yarn generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          BRANCH: gh-pages
          FOLDER: dist
